version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client0:/app/data
  client2:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client1:/app/data
  client3:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client2:/app/data
  client4:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client3:/app/data
  client5:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client4:/app/data
  client6:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client5:/app/data
  client7:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client6:/app/data
  client8:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client7:/app/data
  client9:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client8:/app/data
  client10:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data/10clients/client9:/app/data

